/**
 * Comprehensive All-India Rescue Departments & Regional Disaster Response Bases
 * Covers NDRF Battalions, SDRF Commands, Fire & Emergency Disaster Wings, and Coast Guard Stations.
 */

export const RESCUE_DEPARTMENTS = [
  // --- NATIONAL HQ & NORTHERN ZONE ---
  {
    id: "DEPT-NDRF-HQ",
    name: "NDRF Directorate General & National Command",
    shortName: "NDRF HQ",
    agency: "NDRF",
    type: "National Command HQ",
    zone: "North",
    city: "New Delhi",
    state: "Delhi NCR",
    lat: 28.5908,
    lng: 77.2285,
    address: "Antyodaya Bhawan, CGO Complex, Lodhi Road, New Delhi",
    contact: "011-24363260 / +91 97110 77372",
    emergencyHotline: "1078 (National Toll-Free)",
    satcomFreq: "14.225 MHz UHF",
    readiness: "Immediate (24/7 Strategic Reserve)",
    personnelStrength: 850,
    equipment: [
      "Mobile Satellite Command Vehicle",
      "Airborne Recon Drones (12)",
      "High-Altitude Rescue Kits",
      "HAZMAT CBRN Response Units (4)"
    ],
    jurisdiction: "All-India Strategic Response & Multi-State Coordination"
  },
  {
    id: "DEPT-NDRF-08-GZB",
    name: "NDRF 8th Battalion Regional Command",
    shortName: "NDRF 8th Bn",
    agency: "NDRF",
    type: "Battalion Base",
    zone: "North",
    city: "Ghaziabad",
    state: "Uttar Pradesh / NCR",
    lat: 28.6692,
    lng: 77.4538,
    address: "Govindpuram, Ghaziabad, NCR",
    contact: "+91 120 2766618",
    emergencyHotline: "1070",
    satcomFreq: "14.280 MHz",
    readiness: "Ready (Immediate Dispatch)",
    personnelStrength: 1150,
    equipment: [
      "Inflatable Deep Water Rafts (35)",
      "Hydraulic Concrete Cutters (20)",
      "Canine Search Dog Squads (8)",
      "Advanced Life Support Ambulances (10)"
    ],
    jurisdiction: "Delhi NCR, Western UP, Haryana, Uttarakhand"
  },
  {
    id: "DEPT-SDRF-UK",
    name: "Uttarakhand SDRF High-Altitude & Mountain Rescue HQ",
    shortName: "Uttarakhand SDRF",
    agency: "SDRF",
    type: "Mountain & Flash-Flood Unit",
    zone: "North",
    city: "Dehradun",
    state: "Uttarakhand",
    lat: 30.3165,
    lng: 78.0322,
    address: "Jolly Grant Regional Base, Dehradun, Uttarakhand",
    contact: "+91 135 2710334",
    emergencyHotline: "1070 / 112",
    satcomFreq: "14.195 MHz",
    readiness: "Ready (High-Altitude Standby)",
    personnelStrength: 620,
    equipment: [
      "Avalanche Transceiver Systems",
      "Ropeway Aerial Rescue Kits",
      "River Rafting White-Water Skiffs (15)",
      "Mountain Evacuation Stretchers"
    ],
    jurisdiction: "Garhwal & Kumaon Himalayan Belts, River Basins"
  },
  {
    id: "DEPT-NDRF-07-PB",
    name: "NDRF 7th Battalion Regional Base",
    shortName: "NDRF 7th Bn",
    agency: "NDRF",
    type: "Battalion Base",
    zone: "North",
    city: "Bathinda",
    state: "Punjab",
    lat: 30.2110,
    lng: 74.9455,
    address: "Bibiwala Road, Bathinda, Punjab",
    contact: "+91 164 2240114",
    emergencyHotline: "1070",
    satcomFreq: "14.210 MHz",
    readiness: "Ready (Immediate Dispatch)",
    personnelStrength: 1050,
    equipment: [
      "Flood Water Jet Boats (28)",
      "Heavy Earthmoving Diggers",
      "CBRN Protective Gear",
      "Field Surgical Tents"
    ],
    jurisdiction: "Punjab, Himachal Pradesh, Jammu & Kashmir, Chandigarh"
  },
  {
    id: "DEPT-SDRF-JK",
    name: "Jammu & Kashmir SDRF Quick Response Command",
    shortName: "J&K SDRF",
    agency: "SDRF",
    type: "Quick Response Command",
    zone: "North",
    city: "Srinagar",
    state: "Jammu & Kashmir",
    lat: 34.0837,
    lng: 74.7973,
    address: "Batmaloo Disaster HQ, Srinagar, J&K",
    contact: "+91 194 2452138",
    emergencyHotline: "112",
    satcomFreq: "14.170 MHz",
    readiness: "Ready (Alpine Alert)",
    personnelStrength: 480,
    equipment: [
      "Snow Rescue Skidoos (6)",
      "River Jhelum Inflatable Boats (18)",
      "Underwater Dive Systems",
      "Hypothermia Emergency Kits"
    ],
    jurisdiction: "Kashmir Valley, Jammu Foothills & Pir Panjal"
  },
  {
    id: "DEPT-SDRF-RJ",
    name: "Rajasthan SDRF & Disaster Management Base",
    shortName: "Rajasthan SDRF",
    agency: "SDRF",
    type: "State Response Command",
    zone: "North",
    city: "Jaipur",
    state: "Rajasthan",
    lat: 26.9124,
    lng: 75.7873,
    address: "Ghat Gate SDRF Campus, Jaipur, Rajasthan",
    contact: "+91 141 2605151",
    emergencyHotline: "1070 / 112",
    satcomFreq: "14.230 MHz",
    readiness: "Ready",
    personnelStrength: 550,
    equipment: [
      "Desert Terrain All-Terrain Vehicles (ATVs)",
      "Flash-Flood Evacuation Boats (20)",
      "High-Capacity Water Submersible Pumps",
      "Emergency Mobile Generators"
    ],
    jurisdiction: "Thar Basin, Chambal River Basin, Aravalli Region"
  },

  // --- SOUTHERN ZONE ---
  {
    id: "DEPT-NDRF-04-ARK",
    name: "NDRF 4th Battalion Headquarters (Arakkonam / Chennai)",
    shortName: "NDRF 4th Bn (Chennai Hub)",
    agency: "NDRF",
    type: "Battalion Base",
    zone: "South",
    city: "Arakkonam / Chennai",
    state: "Tamil Nadu",
    lat: 13.0827,
    lng: 80.2707,
    address: "Suraksha Campus, Arakkonam & Chennai Waterfront Depot",
    contact: "+91 4177 246594 / +91 94421 05951",
    emergencyHotline: "1070 / 1077",
    satcomFreq: "14.260 MHz",
    readiness: "Immediate (Coastal & Urban Flood Taskforce)",
    personnelStrength: 1200,
    equipment: [
      "Gemini Heavy Motorized Inflatable Boats (45)",
      "Deep Sea Sonar & Submersible Cameras",
      "Night Reconnaissance Drones (8)",
      "Trauma Life Support Fleet (14)"
    ],
    jurisdiction: "Tamil Nadu, Puducherry, Andaman & Nicobar Islands"
  },
  {
    id: "DEPT-TN-FIRE-DISASTER",
    name: "Tamil Nadu Fire & Rescue Services (TNFRS) State Command",
    shortName: "TNFRS Command",
    agency: "State Fire & Disaster",
    type: "State Headquarters",
    zone: "South",
    city: "Chennai",
    state: "Tamil Nadu",
    lat: 13.0604,
    lng: 80.2496,
    address: "12 Rukmini Lakshmipathi Road, Egmore, Chennai",
    contact: "044-28554316",
    emergencyHotline: "101 / 112",
    satcomFreq: "14.240 MHz",
    readiness: "Immediate",
    personnelStrength: 820,
    equipment: [
      "Turntable Aerial Ladders (55m)",
      "High-Pressure Chemical Tender Vans",
      "Amphibious All-Terrain Rescue Buggies",
      "Rescue Diving Teams"
    ],
    jurisdiction: "Greater Chennai Metropolitan Area & Tamil Nadu Coastline"
  },
  {
    id: "DEPT-NDRF-10-AP",
    name: "NDRF 10th Battalion Regional Command",
    shortName: "NDRF 10th Bn",
    agency: "NDRF",
    type: "Battalion Base",
    zone: "South",
    city: "Vijayawada",
    state: "Andhra Pradesh",
    lat: 16.5062,
    lng: 80.6480,
    address: "Acharya Nagarjuna Nagar, Guntur-Vijayawada Highway",
    contact: "+91 863 2293050",
    emergencyHotline: "1070",
    satcomFreq: "14.215 MHz",
    readiness: "Ready (Cyclone & River Alert)",
    personnelStrength: 1100,
    equipment: [
      "Cyclone Rapid Water Evacuation Boats (40)",
      "Tree & Heavy Debris Clearers",
      "High-Capacity Dewatering Pumps",
      "Satellite Mobile Comms Rig"
    ],
    jurisdiction: "Andhra Pradesh, Telangana, Coastal Bay of Bengal"
  },
  {
    id: "DEPT-TG-DISASTER-HYD",
    name: "Telangana Disaster Response & Fire Services HQ",
    shortName: "Telangana SDRF",
    agency: "SDRF",
    type: "State Command HQ",
    zone: "South",
    city: "Hyderabad",
    state: "Telangana",
    lat: 17.3850,
    lng: 78.4867,
    address: "BRK Bhavan, Tank Bund Road, Hyderabad",
    contact: "040-23442944",
    emergencyHotline: "101 / 112",
    satcomFreq: "14.190 MHz",
    readiness: "Ready",
    personnelStrength: 640,
    equipment: [
      "Urban Flood Response Vehicles",
      "Thermal Drone Detection Systems",
      "Pneumatic Shoring Equipment",
      "Trauma Ambulances"
    ],
    jurisdiction: "Hyderabad Metro & Godavari/Krishna River Basins"
  },
  {
    id: "DEPT-KA-SDRF-BLR",
    name: "Karnataka SDRF & Bengaluru Emergency Relief Base",
    shortName: "Karnataka SDRF",
    agency: "SDRF",
    type: "Regional Response Centre",
    zone: "South",
    city: "Bengaluru",
    state: "Karnataka",
    lat: 12.9716,
    lng: 77.5946,
    address: "M.S. Building & Fire Central Station, Bengaluru",
    contact: "080-22971500",
    emergencyHotline: "1070 / 112",
    satcomFreq: "14.250 MHz",
    readiness: "Ready",
    personnelStrength: 750,
    equipment: [
      "Heavy Urban Dewatering Skids",
      "Hydraulic Rescue Tools",
      "Inflatable Water Boats (24)",
      "Mobile Water Purification Units"
    ],
    jurisdiction: "Karnataka Inland, Western Ghats & Coastal Canara"
  },
  {
    id: "DEPT-KL-DISASTER-KOC",
    name: "Kerala Fire & Rescue Disaster Marine Wing",
    shortName: "Kerala Marine Rescue",
    agency: "State Fire & Disaster",
    type: "Water Rescue & Landslide HQ",
    zone: "South",
    city: "Kochi / Alappuzha",
    state: "Kerala",
    lat: 9.9312,
    lng: 76.2673,
    address: "Club Road, Marine Drive, Kochi, Kerala",
    contact: "0484-2354000",
    emergencyHotline: "101 / 112",
    satcomFreq: "14.270 MHz",
    readiness: "Immediate (Monsoon Standby)",
    personnelStrength: 580,
    equipment: [
      "Backwater Catamaran Rescue Boats",
      "Landslide Acoustic Sensors",
      "SCUBA Heavy Diving Squads",
      "Amphibious Evacuation Carriers"
    ],
    jurisdiction: "Kerala Backwaters, Coastal Belts & Idukki/Wayanad Ghats"
  },

  // --- WESTERN ZONE ---
  {
    id: "DEPT-NDRF-05-PUNE",
    name: "NDRF 5th Battalion Regional Command",
    shortName: "NDRF 5th Bn (Pune)",
    agency: "NDRF",
    type: "Battalion Base",
    zone: "West",
    city: "Pune",
    state: "Maharashtra",
    lat: 18.5204,
    lng: 73.8567,
    address: "Sudumbare Campus, Talegaon-Chakan Road, Pune",
    contact: "+91 2114 247000",
    emergencyHotline: "1070",
    satcomFreq: "14.235 MHz",
    readiness: "Immediate",
    personnelStrength: 1150,
    equipment: [
      "Swift Water Rescue Skiffs (38)",
      "Building Collapse Search Cameras",
      "Chemical Spillage Containment Trailer",
      "Life Support Ambulances (12)"
    ],
    jurisdiction: "Maharashtra, Goa & Western Ghats"
  },
  {
    id: "DEPT-MH-MUMBAI-DISASTER",
    name: "Mumbai Disaster Management & Marine Rescue Cell (MCGM)",
    shortName: "Mumbai Disaster Cell",
    agency: "State Fire & Disaster",
    type: "Metropolitan Command HQ",
    zone: "West",
    city: "Mumbai",
    state: "Maharashtra",
    lat: 19.0760,
    lng: 72.8777,
    address: "Municipal Corporation HQ, Fort, Mumbai",
    contact: "022-22694725",
    emergencyHotline: "1916 / 101",
    satcomFreq: "14.285 MHz",
    readiness: "Immediate (High-Tide & Urban Flood Alert)",
    personnelStrength: 900,
    equipment: [
      "High-Capacity Dewatering Pumping Stations",
      "Harbour Fast Rescue Crafts (6)",
      "Thermal Aerial Survey Drones (10)",
      "Hydraulic Spreaders & Concrete Cutters"
    ],
    jurisdiction: "Mumbai Island City, Suburban Coastline & Thane Basin"
  },
  {
    id: "DEPT-NDRF-06-GUJ",
    name: "NDRF 6th Battalion Regional Base",
    shortName: "NDRF 6th Bn (Gujarat)",
    agency: "NDRF",
    type: "Battalion Base",
    zone: "West",
    city: "Vadodara / Gandhinagar",
    state: "Gujarat",
    lat: 22.3072,
    lng: 73.1812,
    address: "Jarod Campus, Vadodara, Gujarat",
    contact: "+91 2668 274601",
    emergencyHotline: "1070",
    satcomFreq: "14.205 MHz",
    readiness: "Ready",
    personnelStrength: 1050,
    equipment: [
      "Estuary & Gulf Flood Rescue Boats (32)",
      "Industrial Chemical Fire Foam Tenders",
      "Earthquake Collapse Sensor Arrays",
      "Mobile Intensive Care Units"
    ],
    jurisdiction: "Gujarat, Daman & Diu, Dadra & Nagar Haveli"
  },
  {
    id: "DEPT-GOA-DISASTER",
    name: "Goa State Disaster Management & Coastal Rescue Command",
    shortName: "Goa Coastal Rescue",
    agency: "State Fire & Disaster",
    type: "Coastal Response Unit",
    zone: "West",
    city: "Panaji",
    state: "Goa",
    lat: 15.4909,
    lng: 73.8278,
    address: "Secretariat Complex, Porvorim, Panaji, Goa",
    contact: "0832-2419554",
    emergencyHotline: "1077 / 112",
    satcomFreq: "14.215 MHz",
    readiness: "Ready (Marine Standby)",
    personnelStrength: 320,
    equipment: [
      "Jet-Ski Rescue Craft (12)",
      "Inflatable Surf Rescue Boats (16)",
      "Deep Ocean Diver Pods",
      "Mobile Trauma Response Vans"
    ],
    jurisdiction: "Goa Coastline, Mandovi & Zuari River Estuaries"
  },

  // --- EASTERN ZONE ---
  {
    id: "DEPT-NDRF-02-KOL",
    name: "NDRF 2nd Battalion Headquarters",
    shortName: "NDRF 2nd Bn (Kolkata)",
    agency: "NDRF",
    type: "Battalion Base",
    zone: "East",
    city: "Kolkata / Haringhata",
    state: "West Bengal",
    lat: 22.5726,
    lng: 88.3639,
    address: "Haringhata Campus, Nadia & Rajarhat Hub, Kolkata",
    contact: "+91 3473 245005 / +91 94347 42830",
    emergencyHotline: "1070",
    satcomFreq: "14.255 MHz",
    readiness: "Immediate (Cyclone & Sundarbans Standby)",
    personnelStrength: 1200,
    equipment: [
      "Riverine Motorized Inflatable Boats (42)",
      "Mud & Mangrove Tracked Vehicles",
      "Long-Range Satellite Transceivers",
      "Advanced Trauma Field Station"
    ],
    jurisdiction: "West Bengal, Sikkim, Sundarbans & Gangetic Delta"
  },
  {
    id: "DEPT-ODISHA-ODRAF",
    name: "Odisha Disaster Rapid Action Force (ODRAF) Command",
    shortName: "ODRAF Command",
    agency: "SDRF",
    type: "Cyclone & Rapid Action HQ",
    zone: "East",
    city: "Bhubaneswar / Cuttack",
    state: "Odisha",
    lat: 20.2961,
    lng: 85.8245,
    address: "Mundali Campus, Cuttack & State Emergency Ops Centre, Bhubaneswar",
    contact: "0674-2534177",
    emergencyHotline: "1070 / 112",
    satcomFreq: "14.245 MHz",
    readiness: "Immediate (World-Class Cyclone Taskforce)",
    personnelStrength: 1350,
    equipment: [
      "Super-Duty Cyclone Inflatable Boats (50)",
      "Heavy Hydraulic Tree & Pole Cutters (120)",
      "Autonomous Water Rescue Drones (15)",
      "Amphibious All-Terrain Transporters"
    ],
    jurisdiction: "Odisha Coastal Corridors & Mahanadi River Delta"
  },
  {
    id: "DEPT-NDRF-09-PAT",
    name: "NDRF 9th Battalion Regional Base",
    shortName: "NDRF 9th Bn (Patna)",
    agency: "NDRF",
    type: "Battalion Base",
    zone: "East",
    city: "Patna / Bihta",
    state: "Bihar",
    lat: 25.5941,
    lng: 85.1376,
    address: "Bihta Air Force Station Road, Patna, Bihar",
    contact: "+91 6115 252003",
    emergencyHotline: "1070",
    satcomFreq: "14.220 MHz",
    readiness: "Immediate (Ganges Flood Taskforce)",
    personnelStrength: 1100,
    equipment: [
      "River Ganges Water Evacuation Boats (44)",
      "Underwater Dive Scuba Sets",
      "Heavy Silt & Water Suction Pumps",
      "Mobile Field Hospitals"
    ],
    jurisdiction: "Bihar, Kosi Basin, Gandak River & Jharkhand Border"
  },

  // --- CENTRAL ZONE ---
  {
    id: "DEPT-NDRF-11-VAR",
    name: "NDRF 11th Battalion Regional Command",
    shortName: "NDRF 11th Bn (Varanasi)",
    agency: "NDRF",
    type: "Battalion Base",
    zone: "Central",
    city: "Varanasi",
    state: "Uttar Pradesh",
    lat: 25.3176,
    lng: 82.9739,
    address: "Sanskriti Sankul, Chaukaghat, Varanasi, UP",
    contact: "+91 542 2501101",
    emergencyHotline: "1070",
    satcomFreq: "14.265 MHz",
    readiness: "Ready (Ghats & River Rescue Alert)",
    personnelStrength: 1100,
    equipment: [
      "Deep River Patrol Boats (36)",
      "Crowd Crush First-Response Mobile Units",
      "Thermal Infrared Detection Cameras",
      "Trauma Life Support Vans"
    ],
    jurisdiction: "Eastern Uttar Pradesh, Bundelkhand & Madhya Pradesh Border"
  },
  {
    id: "DEPT-MP-SDRF-BHO",
    name: "Madhya Pradesh SDRF Central Command",
    shortName: "MP SDRF Command",
    agency: "SDRF",
    type: "State Command HQ",
    zone: "Central",
    city: "Bhopal",
    state: "Madhya Pradesh",
    lat: 23.2599,
    lng: 77.4126,
    address: "Bhadbhada Road Disaster Centre, Bhopal, MP",
    contact: "0755-2443800",
    emergencyHotline: "1079 / 112",
    satcomFreq: "14.200 MHz",
    readiness: "Ready",
    personnelStrength: 680,
    equipment: [
      "Narmada Basin Motor Boats (26)",
      "Industrial Hazmat Detection Vans",
      "Concrete Breakers & Hydraulic Jacks",
      "Mobile Oxygen Generating Van"
    ],
    jurisdiction: "Narmada, Tapti & Chambal Basins, Central Plateau"
  },
  {
    id: "DEPT-CG-SDRF-RAI",
    name: "Chhattisgarh SDRF & Disaster Management Unit",
    shortName: "Chhattisgarh SDRF",
    agency: "SDRF",
    type: "State Response Base",
    zone: "Central",
    city: "Raipur",
    state: "Chhattisgarh",
    lat: 21.2514,
    lng: 81.6296,
    address: "Mana Camp Disaster Center, Raipur, Chhattisgarh",
    contact: "0771-2412850",
    emergencyHotline: "1070 / 112",
    satcomFreq: "14.185 MHz",
    readiness: "Ready",
    personnelStrength: 420,
    equipment: [
      "Mahanadi Flood Inflatable Boats (18)",
      "Forest Fire Rapid Response Units",
      "High-Mobility Rescue 4x4s",
      "Emergency Stretcher Fleets"
    ],
    jurisdiction: "Bastar, Bilaspur & Raipur Valley"
  },

  // --- NORTH-EASTERN ZONE ---
  {
    id: "DEPT-NDRF-01-GUW",
    name: "NDRF 1st Battalion Regional Headquarters",
    shortName: "NDRF 1st Bn (Guwahati)",
    agency: "NDRF",
    type: "Battalion Base",
    zone: "North-East",
    city: "Guwahati",
    state: "Assam",
    lat: 26.1445,
    lng: 91.7362,
    address: "Patgaon Campus, Rani Road, Kamrup, Guwahati, Assam",
    contact: "+91 361 2849005 / +91 94351 17246",
    emergencyHotline: "1070 / 1077",
    satcomFreq: "14.275 MHz",
    readiness: "Immediate (Brahmaputra Flood Taskforce)",
    personnelStrength: 1200,
    equipment: [
      "Brahmaputra High-Current Jet Boats (46)",
      "Helicopter Air-Drop Preparedness Kits",
      "Earthquake Seismic Life Detectors (12)",
      "Amphibious Evacuation Carriers"
    ],
    jurisdiction: "Assam, Meghalaya, Mizoram, Nagaland, Manipur"
  },
  {
    id: "DEPT-NDRF-12-ITA",
    name: "NDRF 12th Battalion Himalayan Base",
    shortName: "NDRF 12th Bn (Arunachal)",
    agency: "NDRF",
    type: "Battalion Base",
    zone: "North-East",
    city: "Doimukh / Itanagar",
    state: "Arunachal Pradesh",
    lat: 27.0844,
    lng: 93.6053,
    address: "Doimukh Regional Base, Papum Pare, Arunachal Pradesh",
    contact: "+91 360 2277100",
    emergencyHotline: "1070",
    satcomFreq: "14.290 MHz",
    readiness: "Ready (High-Mountain & Landslide Alert)",
    personnelStrength: 850,
    equipment: [
      "Landslide Search Ground Penetrating Radars",
      "Mountain Aerial Cableway Systems",
      "All-Weather High-Altitude Tents",
      "Specialized Cold-Climate Trauma Units"
    ],
    jurisdiction: "Arunachal Pradesh, Eastern Himalayas & River Valleys"
  }
];

export const REGIONAL_ZONES = [
  { id: "all", label: "🇮🇳 All India", center: [21.7679, 78.8718], zoom: 5 },
  { id: "South", label: "Southern Zone", center: [13.0827, 80.2707], zoom: 7 },
  { id: "North", label: "Northern Zone", center: [29.5, 76.5], zoom: 6 },
  { id: "West", label: "Western Zone", center: [19.5, 74.0], zoom: 6 },
  { id: "East", label: "Eastern Zone", center: [22.5, 86.0], zoom: 6 },
  { id: "Central", label: "Central Zone", center: [23.5, 80.5], zoom: 6 },
  { id: "North-East", label: "North-Eastern Zone", center: [26.0, 92.5], zoom: 7 },
  { id: "chennai", label: "Chennai HQ Focus", center: [13.075, 80.265], zoom: 12 }
];
